client:
  config:
    service:
      env: default_env
      zone: embedded
      service: m3db
      etcdClusters:
        - zone: embedded
          endpoints:
            - 172.20.42.15:2379
            # - 172.20.42.16:2379
            # - 172.20.42.17:2379
            # - 172.20.42.12:2379
            # - 127.0.0.1:2379
            # - 172.20.42.13:2379

  writeConsistencyLevel: majority
  readConsistencyLevel: unstrict_majority
